/*
   Example use of HardDiskEncoder.h library (class to handle Hard Disk drives as rotary encoders)
   Author: Alvaro Cassinelli & Pablo Gindel, 18/5/2015
*/

#include <HardDiskEncoder.h>

// Hard disk spindle coils outputs pins (to digital input pins controlling the external interrupts)
// ATTENTION: you will need to check that the order of the coils is good, or it may not work.
#define coilPinA 2
#define coilPinB 3
#define coilPinC 4

#define ANGLE_STEP 15 // In degrees - this is a function of the motor type. Typical values are 24 steps/turn, so the angle
// step is 15 degrees.

HDEncoder* myHDEncoder;

// ===============================================================================================

void setup() {
  Serial.begin(115200);
  myHDEncoder = new HDEncoder(coilPinA, coilPinB, coilPinC, INPUT, CHANGE);
  myHDEncoder->setDegresPerStep(ANGLE_STEP); // by default the angle is set to 15
}

void loop() {

  // 1) Action to take when there is ONE CORRECT encoder change (since the coil current is generated by the electro-motive
  // motion, it may be possible that at very slow speeds the correct thresholds are not achieved. The library will just
  // ignore those changes. As a consequence, it will look like the encoder does not react.
  // In other words: there is a MINIMUM speed for the Hard Drive to work as a rotary encoder. You can play with the Schmitt
  // Trigger thresholds and the capacitor filtering to set the required minimum speed (vs. robustness)

  if (myHDEncoder->isChange()) {

    // Check on serial port the pin data:
    Serial.println(myHDEncoder->getStateString());

    // Check on Serial port the computed quantities (absolute angle and speed):
    Serial.print("Angle (deg): "); Serial.println(myHDEncoder->getAngle(), DEC);
    
    // Note: the speed is computed between ticks: it is then more "reactive", but for more precision in the 
    // case of continuous motions, it may be better to recalculate it from the absolute angle in a fixed time interval 
    Serial.print("Speed (turns/sec): "); Serial.println(myHDEncoder->getSpeed(), DEC);

    Serial.println();
  }

  // 2) ... other things in the loop

}




